# Generated by Django 6.0.3 on 2026-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_restaurantbooking_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelbooking",
            name="advance_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
