# Generated by Django 6.0.3 on 2026-03-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="longitude",
        ),
        migrations.AddField(
            model_name="destination",
            name="short_description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="price_per_night",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="DestinationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="destinations/gallery/")),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="destinations.destination",
                    ),
                ),
            ],
        ),
    ]
