# Generated by Django 6.0.3 on 2026-03-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0002_remove_hotel_latitude_remove_hotel_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
