# Generated by Django 6.0.3 on 2026-04-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0003_destinationlike"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="rating",
        ),
    ]
