# Generated by Django 6.0.3 on 2026-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0006_appfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
